apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: component-sample
  namespace: application-service-system
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: application-sample
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: component-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: component-sample-
      namespace: application-service-system
    spec:
      params:
      - name: git-url
        value: https://github.com/devfile-samples/devfile-sample-java-springboot-basic
      - name: output-image
        value: maysunfaisal/spr:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle@sha256:c36c9216b7740f4acd755d9167dacf559fc1d2ce67fd108cffdedbfb2b1d2fae
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: component-sample/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
